config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :video, only: [:new, :create, :show]
  root 'video#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
	mount_uploader :video, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/video_controller.rb
require 'aws-sdk-s3'

class VideoController < ApplicationController
  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      transcode_and_upload_video
      redirect_to @video, notice: 'Video was successfully uploaded.'
    else
      render :new
    end
  end

	def show
		@video = Video.find(params[:id])
	end

  private

  def video_params
    params.require(:video).permit(:name, :video)
  end

  def transcode_and_upload_video
    video_path = @video.video.path
    transcoded_video_dir = "#{Rails.root}/tmp/#{SecureRandom.hex}"
    FileUtils.mkdir_p(transcoded_video_dir)

    transcoded_video = "#{transcoded_video_dir}/output.mp4"
    transcoder = FFMPEG::Movie.new(video_path)
		options = {
			custom: %w(-c:v libx264 -c:a aac),
			preserve_aspect_ratio: :width,
			resolution: '640x360'
		}
    transcoder.transcode(transcoded_video, options)

    # Upload transcoded video to S3
    s3 = Aws::S3::Resource.new(
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: ENV['AWS_REGION']
    )
    obj = s3.bucket(ENV['S3_BUCKET']).object(File.basename(transcoded_video))
    obj.upload_file(transcoded_video)
    
    # Update the video attribute with the S3 URL
    @video.update(s3_url: obj.public_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoStream</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video/new.html.erb
<%= form_with(model: @video, url: video_index_path, method: :post, html: { multipart: true }) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :video %>
  <%= form.file_field :video %>

  <%= form.submit 'Upload Video' %>
<% end %>

app/views/video/show.html.erb
<link href="https://vjs.zencdn.net/7.19.2/video-js.css" rel="stylesheet" />
<video id="my-video" class="video-js" controls preload="auto" width="640" height="360" data-setup="{}">
  <source src="<%= @video.s3_url %>" type='video/mp4'>
</video>
<script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script>